### ISSUE TITLE
Code for Project#02

### ISSUE THREAD

**Issue by acrobat118** [CrawfordGroup/ProgrammingProjects#25]
Dear Author,
Thank you for creating these projects for new learners like me. I am struggling in ProgrammingProjects/Project#02/ to get the Mass-Weighted Hessian Matrix. I am not properly getting the sequence to divide by masses of mi and mj.  My code is not giving me the right answer. Can you please share the code for this step? Thank you.

**Comment by bgpeyton** [comment]
Hi @acrobat118 , where specifically are you having a problem? We generally try not to share too many extra code snippets, as we encourage people to use their own style. 

Have you reshaped the Hessian matrix properly?

**Comment by acrobat118** [comment]
Actually, I am using FORTRAN for these projects. I read the Hessian and trying to convert each element into mass-weighted inside the reading loop. I could not figure out the sequence of masses mi and mj to be used for each element. I am able to get all elements of mass-weighted correct except elements of row 5 (i.e. 5*1, 5*2, 5*3 ...... 5*9) for water example. Your solutions tips are very helpful but unfortunately I do not have solution code for this step. Your help will be much appreciated.

**Comment by bgpeyton** [comment]
I don't have any FORTRAN code snippets on hand, but perhaps let's take a look at an example from your problem row to start off.

When building your (square) Hessian, how have you ordered your row/columns? You should have, e.g., 9 rows/columns for water, where a row keeps the first derivative constant and the second derivative varies (x1x1, x1y1, x1z1, x1x2, x1y2, x1z2, etc). You then have _natom_ such rows, where the first derivative moves to the next coordinate (y1x1, y1y1, y1z1, y1x2, etc). 

If this is the structure, then row 5 (taking your indexing to start at 1 for FORTRAN) should correspond to the second row of the second atom's coordinates, e.g. Hydrogen's y-coordinate with the various coordinates of the other atom. This should let us track down these values.

The second derivative of the energy wrt y(H)x(O) is 0, so we'll move to the next value. The second derivative wrt y(H)y(O) is (-0.1585663567), while the corresponding masses for O and H are (15.9949146196) and (1.0078250322) a.u., respectively. Using the mass-weighting formula gives us (-0.0394936719), which corresponds to row 5 column two of the [Hint for Step 2](https://github.com/CrawfordGroup/ProgrammingProjects/blob/master/Project%2302/hints/hint2.md). 

Please let me know if/where you'd like me to go into more detail.

**Comment by acrobat118** [comment]
Thank you very much for your quick reply and help. I figured out the problem. Issue was not with my loops or calling of atomic masses as I posted in question. I was allocating less space than required to an array. But thanks for your help and above all, again much thanks for posting these learning projects.
