### ISSUE TITLE
Reading eri.dat in Project#3

### ISSUE THREAD

**Issue by hsulab** [CrawfordGroup/ProgrammingProjects#31]
Dear Authors,

Thank you for such great tutorials. I am struggling in reading the eri.dat. From the hints and the formulae, I calculated the index of <66|66> to be 405 which seems that there should 405+1 elements in the lower triangle matrix. But there are only 228 lines in the eri.dat. Did I misunderstand something in the permutational symmetry? Could you give some more hints?

Many thanks,
Jiayan

**Comment by aromanro** [comment]
Check out the `GetElectronElectronIndex` and `GetTwoIndex` implementation for an example on how to compute the indices, here: https://github.com/aromanro/HartreeFock/blob/master/HartreeFock/IntegralsRepository.h.

By the way, the project implements quite a bit of the proposed projects here, maybe you'll find it useful: https://github.com/aromanro/HartreeFock

**Comment by hsulab** [comment]
> Check out the `GetElectronElectronIndex` and `GetTwoIndex` implementation for an example on how to compute the indices, here: https://github.com/aromanro/HartreeFock/blob/master/HartreeFock/IntegralsRepository.h.
> 
> By the way, the project implements quite a bit of the proposed projects here, maybe you'll find it useful: https://github.com/aromanro/HartreeFock

Thank you for the reply! I received an email days ago, which gave me the hint that the `eri.dat` only contains the non-zero integrals. 

Your repository looks great! I will take a look at it!

**Comment by aromanro** [comment]
Well, that I didn't know, as I compute the integrals in my project, instead of loading it from this file.

Indeed, from this hint: https://github.com/CrawfordGroup/ProgrammingProjects/blob/master/Project%2303/hints/hint3-3.md that seems to be the case.

I guess you should close this issue.

**Comment by hsulab** [comment]
Closed.
